# Generated by Django 2.2.4 on 2019-09-04 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=128)),
                ('target', models.IntegerField(choices=[(1, 'samotne_matki'), (2, 'niepełnosprawni'), (3, 'dzieci'), (4, 'osoby_starsze'), (5, 'bezdomni'), (6, 'bezrobotni'), (7, 'wszyscy')])),
                ('address', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.IntegerField(choices=[(1, 'zabawki'), (2, 'książki'), (3, 'ubrania, które nadają się do ponownego użycia'), (4, 'ubrania do wyrzucenia'), (5, 'inne')])),
                ('number_of_bags', models.IntegerField(default=0)),
                ('recipient_type', models.IntegerField(choices=[(1, 'samotne_matki'), (2, 'niepełnosprawni'), (3, 'dzieci'), (4, 'osoby_starsze'), (5, 'bezdomni'), (6, 'bezrobotni'), (7, 'wszyscy')])),
                ('city', models.CharField(max_length=128)),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
                ('pickup_address', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=128)),
                ('pickup_date', models.DateTimeField()),
                ('transport_notes', models.TextField()),
                ('transfer_status', models.BooleanField(default=False)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plab.Institutions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
