# Generated by Django 2.2.4 on 2019-08-18 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=128)),
                ('target', models.IntegerField(choices=[(1, 'samotne_matki'), (2, 'niepełnosprawni'), (3, 'dzieci'), (4, 'osoby_starsze'), (5, 'bezdomni'), (6, 'bezrobotni'), (7, 'wszyscy')])),
                ('address', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UserDonations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_donations', models.IntegerField()),
                ('nr_bags', models.IntegerField()),
                ('nr_institutions', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('darowizna_type', models.IntegerField(choices=[(1, 'zabawki'), (2, 'książki'), (3, 'ubrania, które nadają się do ponownego użycia'), (4, 'ubrania do wyrzucenia'), (5, 'inne')])),
                ('worki', models.IntegerField()),
                ('odbiorca_type', models.IntegerField(choices=[(1, 'samotne_matki'), (2, 'niepełnosprawni'), (3, 'dzieci'), (4, 'osoby_starsze'), (5, 'bezdomni'), (6, 'bezrobotni'), (7, 'wszyscy')])),
                ('miasto', models.CharField(max_length=128)),
                ('darowizna_date', models.DateTimeField(auto_now_add=True)),
                ('adres_odbioru', models.CharField(max_length=256)),
                ('tel', models.CharField(max_length=32)),
                ('data', models.DateField()),
                ('godzina', models.DateTimeField()),
                ('notatka', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('instytucja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plab.Institutions')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
