# Generated by Django 2.2.4 on 2019-09-05 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plab', '0002_profile1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile1',
        ),
    ]
