# Generated by Django 2.2.4 on 2019-09-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plab', '0003_delete_profile1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutions',
            name='city',
            field=models.CharField(max_length=64),
        ),
    ]
