# Generated by Django 2.2.4 on 2019-09-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plab', '0005_profile1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='pickup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Profile1',
        ),
    ]
