# Generated by Django 2.2.4 on 2019-09-11 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plab', '0007_profile1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donations',
            name='pickup_date',
        ),
    ]
