# Generated by Django 2.2.4 on 2019-09-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plab', '0008_remove_donations_pickup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
