# Generated by Django 2.2.4 on 2019-09-11 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plab', '0009_donations_pickup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='donation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
